flask setup

diff --git a/bin/FoundAIrun b/bin/FoundAIrun
--- a/bin/FoundAIrun
+++ b/bin/FoundAIrun
@@ -2,9 +2,9 @@
 
 set -Eeuo pipefail
 
-if [ ! -f "var/FoundAI.sqlite3" ]; then
-    echo "Error: database does not exist"
-    exit 1
-fi
+# if [ ! -f "var/FoundAI.sqlite3" ]; then
+#     echo "Error: database does not exist"
+#     exit 1
+# fi
 
 flask --app FoundAI --debug run --host 0.0.0.0 --port 8000
